### ISSUE TITLE
admin appeal

### ISSUE THREAD

**Issue by KirbyYT** [ZayBlockBugLine/ZayBlockBugLine#3]
i want to apply for admin

**Comment by ZayBlockBugLine** [comment]
Hey Welcome How May I help You,

**Comment by KirbyYT** [comment]
I want to be admin again

**Comment by ZayBlockBugLine** [comment]
Why????

**Comment by KirbyYT** [comment]
because i want permissions back so i can make unicorns and help the server with issues such like 3toisyou hes an issue i can banish him

**Comment by ZayBlockBugLine** [comment]
OK Remember.... If This Conversation is locked that means its being revived.... If its closed and locked well you have no hope...

**Comment by KirbyYT** [comment]
NO pls

**Comment by KirbyYT** [comment]
I want to be staff pls admin in pacific

**Comment by ZayBlockBugLine** [comment]
Ok why should we make you head admin??

**Comment by KirbyYT** [comment]
admin

**Comment by ZayBlockBugLine** [comment]
Ok why should we make you head admin?? i mean

**Comment by KirbyYT** [comment]
because i like to help people

**Comment by ZayBlockBugLine** [comment]
why do you like help people

**Comment by ZayBlockBugLine** [comment]
# hi

**Comment by KirbyYT** [comment]
becuase i need to help myself i have no life

**Comment by KirbyYT** [comment]
# HI

**Comment by ZayBlockBugLine** [comment]
Ok

**Comment by KirbyYT** [comment]
#2 WHY

**Comment by ZayBlockBugLine** [comment]
Sorry about that

**Comment by ZayBlockBugLine** [comment]
i needed to fix it

**Comment by KirbyYT** [comment]
so am i admin

**Comment by ZayBlockBugLine** [comment]
What Will You Do At The Role HeadAdmin

**Comment by ZayBlockBugLine** [comment]
# NOOOOOOOOOOOOOOOOOO

**Comment by ZayBlockBugLine** [comment]
If this post is closed 
Well Your Admin

**Comment by KirbyYT** [comment]
I will help people such as 3toisyou he needed mental help such as i do so pls you can sponsor me to help me in mental issues

**Comment by ZayBlockBugLine** [comment]
This Post is Closed Forever Plz Reload This Page

**Comment by ZayBlockBugLine** [comment]
MORE DETAILS

**Comment by ZayBlockBugLine** [comment]
# **NOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW**

**Comment by ZayBlockBugLine** [comment]
`fuck u`

**Comment by KirbyYT** [comment]
I want admin because i spent time on this server pls i will help at all cost :)

**Comment by ZayBlockBugLine** [comment]
I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)V

**Comment by ZayBlockBugLine** [comment]
I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)I want admin because i spent time on this server pls i will help at all cost :)VV

**Comment by KirbyYT** [comment]
i want to apply for admin
--

**Comment by KirbyYT** [comment]
i want to apply for admin
-

**Comment by ZayBlockBugLine** [comment]
WHAT THE  FUCKEN HELLL
